Update version check logic
github/gh-gei pull request #1137
Opened 2023-10-17 03:02 UTC by pnsk

- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)
- [ ] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

2023-10-17 12:38 UTC, timrogers approved these changes
This changes makes sense to me - but I'll ask one of our engineers to take a look too ✅ 

I would expect to see tests updated for this change, but from what I can see, this behaviour isn't tested right now, so that wouldn't be a super easy thing to do.

2023-10-17 12:41 UTC, timrogers commented on src/Octoshift/Services/VersionChecker.cs
> +        return latestVersion.CompareTo(curVersion) <= 0;
I do wonder if we should use a semantic versioning library here to properly compare the versions - that would be the safest option - but in practice, I don't think it's necessary.

2023-10-17 17:51 UTC, timrogers requested changes
@pnsk Can you add an entry to `RELEASENOTES.md` like this?:

> Fix version check so that a version later than the latest version published on GitHub isn't considered old

2023-10-18 00:59 UTC, pnsk commented
@timrogers I've updated `RELEASENOTES.md` 😄 

Could you please review this PR again? 🙇 

Thanks!

2023-10-18 10:35 UTC, timrogers approved these changes

2023-10-18 11:21 UTC, merged