Add capability to skip version checks
github/gh-gei pull request #1154
Opened 2023-10-26 15:46 UTC by tspascoal

If  environment variable GEI_SKIP_VERSION_CHECK is set true, no version checks will be performed

Closes #1077 

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)
- [x] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

2023-10-26 19:17 UTC, ArinGhazarian commented on src/ado2gh/Program.cs
> +            if (Environment.GetEnvironmentVariable("GEI_SKIP_VERSION_CHECK")?.ToUpperInvariant() == "TRUE")
same [suggestions](https://github.com/github/gh-gei/pull/1155#discussion_r1373701295) applies here too

2023-10-31 16:15 UTC, timrogers approved these changes
Looks great to me! I have a few suggestions on the docs and copy, just to align with your other PR.

2023-10-31 16:15 UTC, timrogers commented on src/ado2gh/Program.cs
> +                Logger.LogInformation("Skipped latest version check of the ado2gh CLI due to GEI_VERSION_CHECK environment variable");
```suggestion
                Logger.LogInformation("Skipped latest version check due to GEI_VERSION_CHECK environment variable");
```

2023-10-31 16:15 UTC, timrogers commented on src/gei/Program.cs
> +                Logger.LogInformation("Skipped latest version check of the gei CLI due to GEI_VERSION_CHECK environment variable");
```suggestion
                Logger.LogInformation("Skipped latest version check due to GEI_VERSION_CHECK environment variable");
```

2023-12-06 15:00 UTC, timrogers requested changes
This is looking good to me from a code perspective ✨ Can you tweak the release notes as suggested, and then we can get this merged?

2023-12-06 15:00 UTC, timrogers commented on RELEASENOTES.md
> +- Skip GitHub status checking on startup if environment variable `GEI_SKIP_STATUS_CHECK` is set to true.
```suggestion
- Skip latest version check on startup if environment variable `GEI_SKIP_VERSION_CHECK` is set to `true`
```

2023-12-06 15:13 UTC, timrogers approved these changes

2023-12-06 15:58 UTC, timrogers commented
Passed! ✅

2023-12-06 15:58 UTC, merged