Automatically build and release the CLI for the linux-arm64 build target
github/gh-gei pull request #1235
Opened 2024-05-01 19:22 UTC by chtzvt

- [ ] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [x] Issue linked
- [ ] Docs updated (or issue created)
- [ ] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

2024-05-01 19:29 UTC, chtzvt commented
RE https://github.com/github/gh-gei/issues/1230#issuecomment-2078150261-- I've essentially made a carbon copy of Tim's commit for `windows-x86`, but will perform some additional testing in my fork.

2024-05-01 19:32 UTC, chtzvt commented
Or perhaps not... For some reason, none of the workflows in my fork appear in the Actions tab of my fork!

Would love to dispatch the CI workflow and actually test the built `linux-arm64` release.

<img width="1512" alt="image" src="https://github.com/github/gh-gei/assets/7227500/c713642e-1537-425d-8d61-f62ac12eb5f1">

2024-05-01 19:35 UTC, dylan-smith commented
> Or perhaps not... For some reason, none of the workflows in my fork appear in the Actions tab of my fork!
> 
> Would love to dispatch the CI workflow and actually test the built `linux-arm64` release.

When I fork repos I get this in my fork: 
![image](https://github.com/github/gh-gei/assets/1508559/f38fe12e-047d-44f9-b8f8-45b5a943bed7)

2024-06-26 20:22 UTC, chtzvt commented
@dylan-smith I was able to create a [separate fork](https://github.com/packfiles/gh-gei) of this repository, merge this PR into it, and run a modified version of the CI workflow (which removed the E2E integration tests, as their success is required for the `publish` step to proceed but I cannot run them). 

The [modified CI workflow run](https://github.com/packfiles/gh-gei/actions/runs/9685931747) produced working aarch64 builds for Linux in the `publish` step, which I was able to verify as executable on an ARM Linux VM:

![Screenshot 2024-06-26 at 16 17 30](https://github.com/github/gh-gei/assets/7227500/c6898444-517e-42db-be59-21a4e99af27b)

2024-06-26 23:06 UTC, dylan-smith commented
I no longer work on the gei eng team (I just lurk in the repo), so one of the engineers from that team will have to shepherd this PR in.

2024-12-19 01:09 UTC, ArinGhazarian requested changes
Thanks for the contribution. The only thing is `-p:TrimMode=partial` MSBuild property needs to be added to all `dotnet publish` commands prevent full trimming of assemblies. Starting with .NET 7, the default behavior changed from 'partial' to 'full', which will break the CLIs.

2024-12-19 15:23 UTC, chtzvt commented
@ArinGhazarian Thanks for the heads up, and for the suggested edits. I’ve gone ahead and committed them.

If there’s anything else you’d like me to address, I’ll gladly take care of it. Otherwise, we can 🚢 ✨

2025-09-05 16:40 UTC, begonaguereca commented
I am closing this issue down as it has been open for more than a year

2025-09-05 16:40 UTC, closed without merging

2025-11-04 14:17 UTC, deiga commented
@begonaguereca 
This PR answers a need that many of your customers have. 
Would it be possible to reopen this and have repo maintainers respond to review requests instead of closing without giving a reason?