PART 3: Add UploadArchiveToGithubStorageWithMultiPart method
github/gh-gei pull request #1271
Opened 2024-09-25 21:02 UTC by begonaguereca

- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)
- [ ] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

2024-09-30 19:19 UTC, begonaguereca commented on src/Octoshift/Services/GithubApi.cs
> +            response = await _client.PostAsync(url, content);
@ArinGhazarian is this what you envisioned for the return type? https://github.com/github/gh-gei/pull/1275

2024-10-08 16:19 UTC, begonaguereca commented on src/Octoshift/Services/GithubApi.cs
> +            var url = $"https://uploads.github.com/organizations/{org.EscapeDataString()}/gei/archive\\?name\\={archiveName}";
Fixed!

2024-10-08 19:37 UTC, merged

2024-10-08 20:16 UTC, ArinGhazarian requested changes
Dropped some comments mostly around simplifying the code and unit tests. Tests need to be added for `GithubClient` too

2024-10-08 20:16 UTC, ArinGhazarian commented on src/OctoshiftCLI.Tests/Octoshift/Services/GithubApiTests.cs
> +    public async Task UploadArchiveToGithubStorage()
```suggestion
    public async Task UploadArchiveToGithubStorage_Should_Upload_Stream_Content()
```

2024-10-08 20:16 UTC, ArinGhazarian commented on src/OctoshiftCLI.Tests/Octoshift/Services/GithubApiTests.cs
> +            .Setup(m => m.PostAsync(It.IsAny<string>(), It.IsAny<HttpContent>(), null))
Let's make sure that `PostAsync` receives a `StreamContent`:

```suggestion
            .Setup(m => m.PostAsync(It.IsAny<string>(), It.IsAny<StreamContent>(), null))
```

2024-10-08 20:16 UTC, ArinGhazarian commented on src/OctoshiftCLI.Tests/Octoshift/Services/GithubApiTests.cs
> +    public async Task UploadArchiveToGithubStorageWithMultiPart()
We use snaked cased test names throughout the project:

```suggestion
    public async Task UploadArchiveToGithubStorage_Should_Upload_Multipart_Content()
```

2024-10-08 20:16 UTC, ArinGhazarian commented on src/OctoshiftCLI.Tests/Octoshift/Services/GithubApiTests.cs
> +            .Setup(m => m.PostAsync(It.IsAny<string>(), It.IsAny<HttpContent>(), null))
```suggestion
            .Setup(m => m.PostAsync(It.IsAny<string>(), It.IsAny<MultipartFormDataContent>(), null))
```