Added reclaim-mannequin to ado2gh
github/gh-gei pull request #359
Opened 2022-04-24 05:13 UTC by dylan-smith

Issue #356 

- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)

2022-04-25 18:01 UTC, ArinGhazarian requested changes

2022-04-25 18:43 UTC, ArinGhazarian commented on src/ado2gh/Commands/ReclaimMannequinCommand.cs
> +            if (mannequin == null || mannequin.Id == null)
you're right they're not semantically equivalent, my bad 😞

2022-04-26 21:23 UTC, dylan-smith commented
Since we don't have the feature implemented yet to consume this csv, my suggestion is to make this command hidden until we add in the feature that can consume it to claim mannequins in bulk (IsHidden = true on the command).

2022-04-26 23:46 UTC, dylan-smith commented on src/ado2gh/GithubApiFactory.cs
> +        }
I reverted this

2022-04-26 23:46 UTC, dylan-smith commented on src/ado2gh/Commands/ReclaimMannequinCommand.cs
> +            Handler = CommandHandler.Create<string, string, string, bool, bool>(Invoke);
done

2022-04-26 23:47 UTC, dylan-smith commented on src/ado2gh/Commands/ReclaimMannequinCommand.cs
> +            }
done, also done in the gei version of this code

2022-04-27 16:47 UTC, ArinGhazarian approved these changes
💯

2022-04-27 16:48 UTC, merged