Move GHES archive-downloading logic out of `AzureApi`
github/gh-gei pull request #679
Opened 2022-10-11 17:40 UTC by tambling

When we shipped #653, we missed a case where omitting `--azure-storage-connection-string` causes the app to crash, because `AzureApiFactory.Create` was running anyway. After a bit of digging, I discovered that we were using `AzureApi` to make unauthenticated HTTP GETs to download the archives off of the GHES instance. This PR moves `AzureApi.DownloadArchive` into its own class, so that we can encapsulate making unauthenticated HTTP GETs.

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)

2022-10-12 18:02 UTC, ArinGhazarian requested changes

2022-10-12 18:02 UTC, ArinGhazarian commented on src/gei/Commands/MigrateRepoCommand.cs
> +            var handler = new MigrateRepoCommandHandler(log, sourceGithubApiFactory, targetGithubApiFactory, environmentVariableProvider, azureApiFactory, awsApiFactory, new FileDownloader(new HttpCl
All dependencies (except the command handlers) should be registered and injected to the constructor, so here you need to register the `FileDownloader` so you won't need to worry about constructing all dependencies and everything will be constructed for you. To register `FileDownloader` add this to our registrations:

```c#
.AddSingleton<FileDownloader>()
``` 

and then inject it to the constructor.

P.S.: With the new infrastructure changes you'll need to get the `FileDownloader` directly from the `IServiceProvider`:
```c#
var fileDownloader = sp.GetRequiredService<FileDownloader>();
```

2022-10-12 18:10 UTC, ArinGhazarian commented on src/gei/FileDownloader.cs
> +    public virtual async Task<byte[]> DownloadArchive(string fromUrl)
Since this is a generic file downloader I would call this method just `Download`.

2022-10-13 18:46 UTC, dylan-smith approved these changes

2022-10-13 18:48 UTC, dylan-smith commented
You should add a bullet to the release notes about the bug that we fixed (even if it was really the previous refactor that actually fixed it - because I didn't release note it then).

2022-10-14 01:48 UTC, merged