Increase Signed url auth time to avoid fail migrations due to queue times
github/gh-gei pull request #780
Opened 2023-01-12 18:21 UTC by juanmrad

We have noticed that some migrations stay in the queue for too long which causes the Signed URL to be invalid. This pr looks at increasing TTL of the url a bit longer to prevent issues from our users due to queued times.

- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)

2023-01-12 19:13 UTC, dylan-smith commented
My fear with doing this is that it may hide other problems. E.g. the recent migration that got stuck in the queue for 37 hours, if this timeout was 48hours we probably would have never noticed that we had a problem.

Interested in @timrogers opinion on this

2023-01-12 20:29 UTC, brianaj approved these changes

2023-01-13 12:08 UTC, timrogers commented
> My fear with doing this is that it may hide other problems. E.g. the recent migration that got stuck in the queue for 37 hours, if this timeout was 48hours we probably would have never noticed that we had a problem.
> 
> Interested in @timrogers opinion on this

All in all, I think this is the right change to make. 

The `generate-script` floe encourages people to queue up many migrations at once and then wait for us to burn through the queue. At the moment, that isn't a viable strategy beyond a certain size because your archive URLs will expire. I think we should extend the validity

That said, we should also improve our instrumentation to address the concern you raised and give us a better view of how long migrations are getting queued for.

I suspect that some customers will be concerned by the security implications of longer signed URL validity. We may at some point want to make this configurable, but I don't think it's necessary now.

2023-01-13 15:16 UTC, timrogers approved these changes

2023-01-13 17:02 UTC, dylan-smith requested changes
can we add a bullet to the release notes please to let customers know

2023-01-13 17:56 UTC, dylan-smith commented on RELEASENOTES.md
> +- Extend the validity of blob storage signed URLs so migration can still be successful even if there is a long queue of migrations
```suggestion
- Extend the expiration of blob storage signed URLs from 24hrs to 48hrs so migration can still be successful even if there is a long queue of migrations
```

2023-01-13 18:02 UTC, dylan-smith commented
FYI looks like the failed integration test was due to this known bug: https://github.com/github/octoshift/issues/5688

2023-01-13 18:06 UTC, dylan-smith approved these changes

2023-01-13 18:21 UTC, merged