Make generated migration scripts more robust if queueing one migration fails
github/gh-gei pull request #811
Opened 2023-02-10 16:59 UTC by timrogers

Customers often use migration scripts generated with `gh gei generate-script` to queue up many migrations.

If queueing up one migration fails, then at the moment, the entire script explodes. This most often happens due to a transient network error when talking to GitHub.com or because archive generation fails in GitHub Enterprise Server.

This is a pretty painful experience, since customers will often leave the script running unattended (e.g. overnight), so they won't know when it terminates and they won't be able to intervene.

This changes the behaviour of our generated scripts so that, if one migration cannot be queued, we print out an error and move on to the next one.

If we have failed to queue up a migration, if applicable, it will be included in the "failed migrations" count printed at the end of the script and we will not attempt to download logs if the `--download-migration-logs` option was selected.

_I haven't written tests for this at the moment. Before I do that, I just wanted to get a review of my approach, since I wrote this code in a bit of a vacuum on a plane._

Fixes https://github.com/github/gh-gei/issues/781.

- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [ ] Issue linked
- [ ] Docs updated (or issue created)

2023-02-10 17:03 UTC, timrogers commented on src/gei/Handlers/GenerateScriptCommandHandler.cs
> +        content.AppendLine("$RepoMigrations = [ordered]@{}");
Recording this allows us to know what migrations generated an ID, and therefore what migrations we should wait for.

2023-02-10 17:03 UTC, timrogers commented on src/gei/Handlers/GenerateScriptCommandHandler.cs
> +        return $"if ($RepoMigrations[\"{repoMigrationKey}\"]) {{ gh gei wait-for-migration --migration-id $RepoMigrations[\"{repoMigrationKey}\"]\nif ($lastexitcode -eq 0) {{ $Succeeded++ }} else {{
There is probably a better way to write this as a multi-line string

2023-02-10 17:03 UTC, timrogers commented on src/gei/Handlers/GenerateScriptCommandHandler.cs
> +        return $"if ($RepoMigrations[\"{targetRepo}\"]) {{ gh gei download-logs --github-target-org \"{githubTargetOrg}\" --target-repo \"{targetRepo}\" }}";
We only want to download the logs if a migration ID was recorded for the repo. If no migration started, we can skip it.

2023-02-10 17:03 UTC, timrogers commented on src/gei/Handlers/GenerateScriptCommandHandler.cs
> -                content.AppendLine("if ($lastexitcode -eq 0) { $Succeeded++ } else { $Failed++ }");
This has now moved inside `WaitForMigrationScript`.

2023-02-24 18:21 UTC, dylan-smith commented
Can somebody include an example of a script before and after this change, easier to understand if we can look at the actual script instead of trying to mentally model the string concat logic.

2023-02-24 22:27 UTC, ArinGhazarian requested changes

2023-02-24 22:27 UTC, ArinGhazarian commented on src/gei/Handlers/GenerateScriptCommandHandler.cs
> +        content.AppendLine("$global:failed = 0");
based on what I already mentioned for `Exec` we cannot do this.

2023-02-25 01:23 UTC, ArinGhazarian commented
@timrogers I am working on a new PR to address this issue for all `generate-script` commands.

2023-02-26 13:39 UTC, timrogers commented
Closing this in favour of @ArinGhazarian's upcoming implementation.  I just wrote this during a flight for a bit of fun, so I'm not at all precious about it ❤️

2023-02-26 13:40 UTC, closed without merging